# node.js server "build"

SHELL := /bin/bash
NODE_PATH = $(shell ./find-node-or-install)
PATH := $(NODE_PATH):$(shell echo $$PATH)

all:
	npm install express
	npm install express-session
	npm install mysql

install:
	

clean:
	
